/**
 * Generate and check the checked-in API Extractor reports.
 *
 * `generate` runs API Extractor for each public-authoritative config and writes
 * the reports under the package's `etc/` directory. `check` uses a temporary
 * report directory, compares the generated bytes with the committed reports,
 * validates the surface map, and applies the deterministic changeset gate.
 */
import { basename, dirname, join, relative, resolve } from "node:path";
import { Extractor, ExtractorConfig } from "@microsoft/api-extractor";
import { logger } from "@weaveio/weave-engine";
import { err, errAsync, ok, okAsync, Result, ResultAsync } from "neverthrow";
import {
  API_SURFACE_MAP,
  type ApiSurfaceMap,
  type PublicApiSurface,
  validateRepositoryApiSurfaceMap,
} from "./api-surface-map.js";

const log = logger.child({ module: "api-reports" });

export const API_REPORT_COMMANDS = ["generate", "check"] as const;
export type ApiReportCommand = (typeof API_REPORT_COMMANDS)[number];

export interface ApiExtractorRun {
  readonly configPath: string;
  readonly reportPath: string;
  readonly changed: boolean;
}

export interface ApiReportRun {
  readonly command: ApiReportCommand;
  readonly reports: readonly ApiExtractorRun[];
  readonly drifted: readonly string[];
}

export interface ApiReportComparison {
  readonly configPath: string;
  readonly packageName: string;
  readonly reportPath: string;
  readonly changed: boolean;
  readonly addedLines: readonly string[];
  readonly removedLines: readonly string[];
  readonly breaking: boolean;
}

export interface ApiChangeset {
  readonly path: string;
  readonly packageNames: readonly string[];
  /** Kept for simple callers; `bumps` is authoritative when present. */
  readonly bump: "patch" | "minor" | "major";
  readonly bumps?: Readonly<Record<string, "patch" | "minor" | "major">>;
  readonly breaking: boolean;
}

export type ApiReportsError =
  | {
      readonly type: "InvalidApiReportsCommand";
      readonly value: string;
    }
  | {
      readonly type: "SurfaceMapInvalid";
      readonly cause: unknown;
    }
  | {
      readonly type: "Filesystem";
      readonly path: string;
      readonly operation: "read" | "mkdir" | "remove" | "list";
    }
  | {
      readonly type: "ExtractorFailed";
      readonly configPath: string;
      readonly messages: readonly string[];
    }
  | {
      readonly type: "ExtractorException";
      readonly configPath: string;
    }
  | {
      readonly type: "ApiReportReadFailed";
      readonly path: string;
    }
  | {
      readonly type: "ApiReportDriftMissingChangeset";
      readonly configPath: string;
      readonly packageName: string;
      readonly removedLines: readonly string[];
    }
  | {
      readonly type: "ApiReportBreakingMissingMarker";
      readonly configPath: string;
      readonly packageName: string;
    }
  | {
      readonly type: "ApiReportBreakingBumpMismatch";
      readonly configPath: string;
      readonly packageName: string;
      readonly bump: string;
    }
  | {
      readonly type: "MalformedChangeset";
      readonly path: string;
    }
  | {
      readonly type: "ChangesetReadFailed";
      readonly path: string;
    }
  | {
      readonly type: "UnexpectedApiReportsFailure";
      readonly message: string;
    };

export interface ApiReportCompatibilityInput {
  readonly comparisons: readonly ApiReportComparison[];
  readonly changesets: readonly ApiChangeset[];
}

/**
 * Compare report lines without treating CRLF/LF differences as API changes.
 * The report header and code fences remain in the snapshots, while compatibility
 * classification considers only signatures and release-tag lines.
 */
export function compareApiReportText(
  before: string,
  after: string,
  input: {
    readonly configPath: string;
    readonly packageName: string;
    readonly reportPath: string;
  },
): ApiReportComparison {
  const beforeLines = normalizeReportLines(before);
  const afterLines = normalizeReportLines(after);
  const beforeSet = new Set(beforeLines);
  const afterSet = new Set(afterLines);
  const removedLines = beforeLines.filter((line) => !afterSet.has(line));
  const addedLines = afterLines.filter((line) => !beforeSet.has(line));
  const breaking = removedLines.some(isBreakingApiLine);
  return {
    ...input,
    changed: removedLines.length > 0 || addedLines.length > 0,
    addedLines,
    removedLines,
    breaking,
  };
}

/** Enforces the report-drift, changeset, and pre-1.0 breaking policy. */
export function validateApiReportCompatibility(
  input: ApiReportCompatibilityInput,
): Result<void, ApiReportsError> {
  for (const comparison of input.comparisons) {
    if (!comparison.changed) continue;
    const matching = input.changesets.filter((changeset) =>
      changeset.packageNames.includes(comparison.packageName),
    );
    if (matching.length === 0)
      return err({
        type: "ApiReportDriftMissingChangeset",
        configPath: comparison.configPath,
        packageName: comparison.packageName,
        removedLines: comparison.removedLines,
      });
    if (!comparison.breaking) continue;
    const breaking = matching.find((changeset) => changeset.breaking);
    if (breaking === undefined)
      return err({
        type: "ApiReportBreakingMissingMarker",
        configPath: comparison.configPath,
        packageName: comparison.packageName,
      });
    const bump = breaking.bumps?.[comparison.packageName] ?? breaking.bump;
    if (bump !== "minor")
      return err({
        type: "ApiReportBreakingBumpMismatch",
        configPath: comparison.configPath,
        packageName: comparison.packageName,
        bump,
      });
  }
  return ok(undefined);
}

/** Parses the small, stable subset of Changesets needed by this gate. */
export function parseApiChangeset(
  path: string,
  contents: string,
): Result<ApiChangeset, ApiReportsError> {
  const lines = contents.replaceAll("\r\n", "\n").split("\n");
  if (lines[0] !== "---") return err({ type: "MalformedChangeset", path });
  const end = lines.indexOf("---", 1);
  if (end === -1) return err({ type: "MalformedChangeset", path });
  const packageNames: string[] = [];
  const bumps: Record<string, "patch" | "minor" | "major"> = {};
  let bump: "patch" | "minor" | "major" | undefined;
  for (const line of lines.slice(1, end)) {
    const match =
      /^\s*["']?([^"':\s]+)["']?\s*:\s*(patch|minor|major)\s*$/.exec(line);
    if (match === null) continue;
    const packageName = match[1];
    const parsedBump = match[2];
    if (
      parsedBump !== "patch" &&
      parsedBump !== "minor" &&
      parsedBump !== "major"
    )
      return err({ type: "MalformedChangeset", path });
    if (packageName !== undefined) {
      packageNames.push(packageName);
      bumps[packageName] = parsedBump;
    }
    bump ??= parsedBump;
  }
  if (packageNames.length === 0 || bump === undefined)
    return err({ type: "MalformedChangeset", path });
  return ok({
    path,
    packageNames: [...new Set(packageNames)],
    bump,
    bumps,
    breaking: lines
      .slice(end + 1)
      .some((line) => /^\s*Breaking:\s*\S/.test(line)),
  });
}

/** Reads pending changesets without importing release planning state. */
export function loadApiChangesets(
  root: string,
): ResultAsync<readonly ApiChangeset[], ApiReportsError> {
  const directory = join(root, ".changeset");
  return ResultAsync.fromPromise(
    Array.fromAsync(new Bun.Glob("*.md").scan({ cwd: directory })),
    () => ({
      type: "Filesystem" as const,
      path: directory,
      operation: "list" as const,
    }),
  ).andThen((files) => {
    let result: ResultAsync<ApiChangeset[], ApiReportsError> = okAsync([]);
    for (const file of files.sort()) {
      if (file === "README.md") continue;
      const path = join(directory, file);
      result = result.andThen((changesets) =>
        ResultAsync.fromPromise(Bun.file(path).text(), () => ({
          type: "ChangesetReadFailed" as const,
          path,
        })).andThen((contents) =>
          liftResult(parseApiChangeset(path, contents)).map((changeset) => [
            ...changesets,
            changeset,
          ]),
        ),
      );
    }
    return result;
  });
}

/** Runs Extractor for every authoritative config and updates `etc/`. */
export function generateApiReports(
  root: string = resolve(import.meta.dir, "../.."),
  map: ApiSurfaceMap = API_SURFACE_MAP,
): ResultAsync<ApiReportRun, ApiReportsError> {
  return validateRepositoryApiSurfaceMap(root, {
    map,
    requireReports: false,
  })
    .mapErr((cause) => ({ type: "SurfaceMapInvalid" as const, cause }))
    .andThen(() => runExtractors(root, map, undefined))
    .andThen((reports) =>
      validateRepositoryApiSurfaceMap(root, { map })
        .mapErr((cause) => ({ type: "SurfaceMapInvalid" as const, cause }))
        .map(() => ({
          command: "generate" as const,
          reports,
          drifted: reports
            .filter((report) => report.changed)
            .map((report) => report.reportPath),
        })),
    );
}

/** Regenerates reports in an ignored temporary directory and applies the gate. */
export function checkApiReports(
  root: string = resolve(import.meta.dir, "../.."),
  map: ApiSurfaceMap = API_SURFACE_MAP,
): ResultAsync<ApiReportRun, ApiReportsError> {
  return ResultAsync.fromPromise(checkApiReportsInternal(root, map), () => ({
    type: "UnexpectedApiReportsFailure" as const,
    message: "the API report check failed before it produced a typed result",
  })).andThen((result) => liftResult(result));
}

export function runApiReports(
  command: string,
  root: string = resolve(import.meta.dir, "../.."),
): ResultAsync<ApiReportRun, ApiReportsError> {
  if (!isApiReportCommand(command))
    return errAsync({
      type: "InvalidApiReportsCommand",
      value: command,
    });
  return command === "generate"
    ? generateApiReports(root)
    : checkApiReports(root);
}

async function checkApiReportsInternal(
  root: string,
  map: ApiSurfaceMap,
): Promise<Result<ApiReportRun, ApiReportsError>> {
  const surfaceMap = await validateRepositoryApiSurfaceMap(root, { map });
  if (surfaceMap.isErr())
    return err({ type: "SurfaceMapInvalid", cause: surfaceMap.error });

  const temporary = await createTemporaryDirectory(root);
  if (temporary.isErr()) return err(temporary.error);
  const tempRoot = temporary.value;

  let finalResult: Result<ApiReportRun, ApiReportsError>;
  const runs = await runExtractors(root, map, tempRoot);
  if (runs.isErr()) {
    finalResult = err(runs.error);
  } else {
    const comparisons = await compareReports(root, map, runs.value, tempRoot);
    if (comparisons.isErr()) {
      finalResult = err(comparisons.error);
    } else {
      const changesets = await loadApiChangesets(root);
      if (changesets.isErr()) {
        finalResult = err(changesets.error);
      } else {
        const compatibility = validateApiReportCompatibility({
          comparisons: comparisons.value,
          changesets: changesets.value,
        });
        if (compatibility.isErr()) {
          finalResult = err(compatibility.error);
        } else {
          finalResult = ok({
            command: "check",
            reports: comparisons.value.map((comparison) => ({
              configPath: comparison.configPath,
              reportPath: comparison.reportPath,
              changed: comparison.changed,
            })),
            drifted: comparisons.value
              .filter((comparison) => comparison.changed)
              .map((comparison) => comparison.reportPath),
          });
        }
      }
    }
  }

  const removed = await removeTemporaryDirectory(tempRoot);
  if (removed.isErr()) return err(removed.error);
  return finalResult;
}

function runExtractors(
  root: string,
  map: ApiSurfaceMap,
  temporaryRoot: string | undefined,
): ResultAsync<readonly ApiExtractorRun[], ApiReportsError> {
  const entries = uniquePublicEntries(map.public);
  let result: ResultAsync<ApiExtractorRun[], ApiReportsError> = okAsync([]);
  for (const entry of entries) {
    result = result.andThen((runs) =>
      runExtractor(root, entry, temporaryRoot).map((run) => [...runs, run]),
    );
  }
  return result;
}

function runExtractor(
  root: string,
  entry: PublicApiSurface,
  temporaryRoot: string | undefined,
): ResultAsync<ApiExtractorRun, ApiReportsError> {
  const configPath = entry.configPath;
  const absoluteConfigPath = resolve(root, configPath);
  const reportName = basename(entry.reportPath, ".api.md");
  const reportFolder =
    temporaryRoot === undefined
      ? resolve(root, dirname(entry.reportPath))
      : join(temporaryRoot, dirname(entry.reportPath));
  return ensureDirectory(reportFolder).andThen(() =>
    liftResult(
      Result.fromThrowable(
        () => {
          const configObject = ExtractorConfig.loadFile(absoluteConfigPath);
          configObject.apiReport = {
            enabled: true,
            reportFolder,
            reportTempFolder: reportFolder,
            reportFileName: reportName,
          };
          const config = ExtractorConfig.prepare({
            configObject,
            configObjectFullPath: absoluteConfigPath,
            packageJsonFullPath: join(
              dirname(absoluteConfigPath),
              "package.json",
            ),
            ignoreMissingEntryPoint: false,
          });
          const messages: string[] = [];
          const extraction = Extractor.invoke(config, {
            localBuild: true,
            showVerboseMessages: false,
            messageCallback: (message) => messages.push(message.toString()),
          });
          return { extraction, messages };
        },
        () => ({ type: "ExtractorException" as const, configPath }),
      )(),
    ).andThen(({ extraction, messages }) => {
      if (!extraction.succeeded)
        return err({
          type: "ExtractorFailed" as const,
          configPath,
          messages,
        });
      return ok({
        configPath,
        reportPath: posixPath(
          temporaryRoot === undefined
            ? entry.reportPath
            : relative(
                temporaryRoot,
                join(reportFolder, `${reportName}.api.md`),
              ),
        ),
        changed: extraction.apiReportChanged,
      });
    }),
  );
}

function compareReports(
  root: string,
  map: ApiSurfaceMap,
  runs: readonly ApiExtractorRun[],
  temporaryRoot: string,
): ResultAsync<readonly ApiReportComparison[], ApiReportsError> {
  let result: ResultAsync<ApiReportComparison[], ApiReportsError> = okAsync([]);
  for (const run of runs) {
    const entry = map.public.find(
      (candidate) => candidate.configPath === run.configPath,
    );
    if (entry === undefined) continue;
    const temporaryPath = join(temporaryRoot, run.reportPath);
    const committedPath = join(root, entry.reportPath);
    result = result.andThen((comparisons) =>
      readText(committedPath).andThen((before) =>
        readText(temporaryPath).map((after) => [
          ...comparisons,
          compareApiReportText(before, after, {
            configPath: entry.configPath,
            packageName: entry.packageName,
            reportPath: entry.reportPath,
          }),
        ]),
      ),
    );
  }
  return result;
}

function uniquePublicEntries(
  entries: readonly PublicApiSurface[],
): readonly PublicApiSurface[] {
  const seen = new Set<string>();
  const unique: PublicApiSurface[] = [];
  for (const entry of entries) {
    if (seen.has(entry.configPath)) continue;
    seen.add(entry.configPath);
    unique.push(entry);
  }
  return unique;
}

function normalizeReportLines(contents: string): readonly string[] {
  return contents
    .replaceAll("\r\n", "\n")
    .split("\n")
    .map((line) => line.trimEnd());
}

function isBreakingApiLine(line: string): boolean {
  const trimmed = line.trim();
  if (trimmed.length === 0 || trimmed.startsWith("//")) return false;
  if (/@(?:public|beta|alpha|internal)\b/.test(trimmed)) return true;
  if (
    /^(?:export\s+)?(?:declare\s+)?(?:class|interface|type|function|const|enum|namespace)\b/.test(
      trimmed,
    )
  )
    return true;
  return /^(?:readonly\s+)?[A-Za-z_$][\w$]*\??\s*(?::|\(|<)/.test(trimmed);
}

function ensureDirectory(path: string): ResultAsync<void, ApiReportsError> {
  return ResultAsync.fromThrowable(
    () => Bun.spawn(["mkdir", "-p", path]).exited,
    () => ({
      type: "Filesystem" as const,
      path,
      operation: "mkdir" as const,
    }),
  )().andThen((exitCode) =>
    exitCode === 0
      ? okAsync(undefined)
      : errAsync({
          type: "Filesystem" as const,
          path,
          operation: "mkdir" as const,
        }),
  );
}

function createTemporaryDirectory(
  root: string,
): ResultAsync<string, ApiReportsError> {
  const path = join(root, "tmp", `api-reports-${crypto.randomUUID()}`);
  return ensureDirectory(path).map(() => path);
}

function removeTemporaryDirectory(
  path: string,
): ResultAsync<void, ApiReportsError> {
  return ResultAsync.fromThrowable(
    () => Bun.spawn(["rm", "-rf", path]).exited,
    () => ({
      type: "Filesystem" as const,
      path,
      operation: "remove" as const,
    }),
  )().andThen((exitCode) =>
    exitCode === 0
      ? okAsync(undefined)
      : errAsync({
          type: "Filesystem" as const,
          path,
          operation: "remove" as const,
        }),
  );
}

function readText(path: string): ResultAsync<string, ApiReportsError> {
  return ResultAsync.fromPromise(Bun.file(path).text(), () => ({
    type: "ApiReportReadFailed" as const,
    path,
  }));
}

function liftResult<T, E>(result: Result<T, E>): ResultAsync<T, E> {
  return result.isOk() ? okAsync(result.value) : errAsync(result.error);
}

function isApiReportCommand(value: string): value is ApiReportCommand {
  return API_REPORT_COMMANDS.some((command) => command === value);
}

function posixPath(path: string): string {
  return path.replaceAll("\\", "/");
}

if (import.meta.main) {
  const command = Bun.argv[2] ?? "check";
  const result = await runApiReports(command);
  if (result.isErr()) {
    log.error({ error: result.error }, "API report command failed");
    process.exitCode = 1;
  } else {
    log.info(
      {
        command: result.value.command,
        reports: result.value.reports.length,
        drifted: result.value.drifted.length,
      },
      "API report command complete",
    );
  }
}
