import {
  type AgentConfig,
  parseModelIntentEntry,
  type ThinkingLevelDecl,
} from "@weaveio/weave-core";

/**
 * Last-resort model used only when adapters provide no override, UI-selected
 * model, Weave model preferences, or system default.
 */
export const DEFAULT_FALLBACK_MODEL = "claude-sonnet-4-5";

/** Explicit model intent plus adapter-owned harness context. */
export interface ModelResolutionInput {
  /** Logical agent name from the normalized Weave config. */
  agentName: string;
  /** Adapter-facing mode metadata from the agent descriptor. */
  agentMode?: AgentConfig["mode"];
  /** Ordered model preferences declared by the agent descriptor. */
  agentModels?: string[];
  /** Ordered model preferences supplied by category context. */
  categoryModels?: string[];
  /** Hard adapter/harness per-agent override. */
  overrideModel?: string;
  /** Harness UI-selected model, when the adapter can supply one. */
  uiSelectedModel?: string;
  /** Harness/system default model. */
  systemDefault?: string;
  /** Optional adapter-supplied model registry for availability filtering. */
  availableModels?: Set<string>;
}

/** Provenance of the selected model candidate. */
export type ResolutionSource =
  | "override"
  | "ui-selected"
  | "category-preference"
  | "agent-preference"
  | "system-default"
  | "constant-fallback";

/** Resolved model plus the priority branch that selected it. */
export interface ModelResolutionResult {
  /** Base model identifier, never including a `#<thinking-level>` suffix. */
  model: string;
  source: ResolutionSource;
  /** Thinking intent attached to the winning model entry, when present. */
  thinkingLevel?: ThinkingLevelDecl;
}

/**
 * Resolve adapter-facing model intent with explicit harness context.
 *
 * This helper is pure and never queries harness UI or model registry state by
 * itself. Adapters decide which optional harness values to pass in. Model
 * preference entries are parsed before availability matching, so a suffixed
 * entry matches the supplied base-model registry and returns its thinking
 * intent alongside the selected model.
 *
 * **Review variant semantics** — review variants generated by
 * `generateReviewVariants()` carry `mode: "subagent"` and `models: [reviewModel]`
 * (a single-element list containing the exact review model). Because subagents
 * skip the `ui-selected` priority branch and carry no `categoryModels`, resolution
 * falls directly to `agent-preference`, which parses the raw preference into the
 * base `model` plus an optional `thinkingLevel`.
 * No separate `"review-variant"` source is needed: the single-element list already
 * makes the intent unambiguous, and the `agent-preference` source accurately
 * describes the mechanism. This is the correct resolution path for any subagent
 * with a pinned model list.
 */
export function resolveAdapterModelIntent(
  input: ModelResolutionInput,
): ModelResolutionResult {
  if (input.overrideModel !== undefined) {
    return resolved(input.overrideModel, "override");
  }

  if (input.uiSelectedModel !== undefined && input.agentMode !== "subagent") {
    return resolved(input.uiSelectedModel, "ui-selected");
  }

  const categoryModel = firstAvailable(
    input.categoryModels,
    input.availableModels,
  );
  if (categoryModel !== undefined) {
    return withSource(categoryModel, "category-preference");
  }

  const agentModel = firstAvailable(input.agentModels, input.availableModels);
  if (agentModel !== undefined) {
    return withSource(agentModel, "agent-preference");
  }

  if (input.systemDefault !== undefined) {
    return resolved(input.systemDefault, "system-default");
  }

  return resolved(DEFAULT_FALLBACK_MODEL, "constant-fallback");
}

function firstAvailable(
  models: string[] | undefined,
  availableModels: Set<string> | undefined,
): ModelIntentCandidate | undefined {
  if (models === undefined) return undefined;

  for (const raw of models) {
    const candidate = parseCandidate(raw);
    if (isAvailable(candidate.model, availableModels)) return candidate;
  }

  return undefined;
}

type ModelIntentCandidate = {
  model: string;
  thinkingLevel?: ThinkingLevelDecl;
};

function parseCandidate(raw: string): ModelIntentCandidate {
  const parsed = parseModelIntentEntry(raw);
  if (parsed.isErr()) return { model: raw };
  return {
    model: parsed.value.baseModel,
    thinkingLevel: parsed.value.thinkingLevel,
  };
}

function isAvailable(
  model: string,
  availableModels: Set<string> | undefined,
): boolean {
  if (availableModels === undefined) return true;
  return availableModels.has(model);
}

function resolved(
  raw: string,
  source: ResolutionSource,
): ModelResolutionResult {
  const candidate = parseCandidate(raw);
  return withSource(candidate, source);
}

function withSource(
  candidate: ModelIntentCandidate,
  source: ResolutionSource,
): ModelResolutionResult {
  if (candidate.thinkingLevel === undefined) {
    return { model: candidate.model, source };
  }
  return {
    model: candidate.model,
    source,
    thinkingLevel: candidate.thinkingLevel,
  };
}
