/**
 * Migration write orchestration.
 *
 * Handles the read-check-write-validate sequence for migrating a legacy
 * JSONC config to a new DSL config file. Validation runs before any file
 * mutation so that invalid generated DSL cannot corrupt the destination.
 */

import { resolve } from "node:path";
import { parseConfig } from "@weaveio/weave-core";
import { errAsync, okAsync, ResultAsync } from "neverthrow";
import { describeFileSystemError, type FileSystem } from "../fs/file-system.js";
import { convertLegacySource } from "./legacy-prompt-files.js";
import type {
  ConversionResult,
  ConversionWarning,
  LegacyConversionError,
  MigratedPromptFile,
  MigrationPlan,
} from "./types.js";

// ---------------------------------------------------------------------------
// DSL content builder
// ---------------------------------------------------------------------------

function commentLine(text: string): string {
  return `# ${text.replace(/[\r\n]+/g, " ")}`.trimEnd();
}

/**
 * Build migrated config.weave content with a provenance comment.
 *
 * Skipped legacy fields are recorded as comments so the file explains what
 * was not carried over. Migration never invents settings: when nothing could
 * be converted, the file holds only these comments.
 */
export function buildMigratedContent(
  plan: MigrationPlan,
  conversion: ConversionResult,
): string {
  const lines = [
    `# Migrated from legacy OpenCode JSONC config`,
    `# Source: ${plan.sourcePath}`,
    `# Scope: ${plan.scope}`,
    `# Generated by: weave init migrate`,
  ];
  if (conversion.warnings.length > 0) {
    lines.push("#", "# Legacy fields that were not migrated:");
    for (const warning of conversion.warnings) {
      lines.push(commentLine(`  - ${warning.field}: ${warning.reason}`));
    }
  }
  if (conversion.dsl.trim().length === 0) {
    lines.push("#", "# No legacy settings could be converted.");
  }
  lines.push("");

  const body = conversion.dsl.trim().length > 0 ? `${conversion.dsl}\n` : "";
  return lines.join("\n") + body;
}

/** Explain why a failed conversion wrote nothing. */
export function describeFailedConversion(error: LegacyConversionError): string {
  const reasons = error.warnings.map(
    (warning) => `  • ${warning.field}: ${warning.reason}`,
  );
  return [
    "The legacy config could not be converted, so nothing was written.",
    ...reasons,
  ].join("\n");
}

// ---------------------------------------------------------------------------
// Write with validation gate
// ---------------------------------------------------------------------------

function fsError(error: Parameters<typeof describeFileSystemError>[0]): {
  message: string;
} {
  return { message: describeFileSystemError(error) };
}

/**
 * Write one migrated prompt file, backing up a differing existing file to
 * `<file>.bak` first. An identical existing file is left untouched.
 */
function writePromptFile(
  fs: FileSystem,
  promptsDir: string,
  promptFile: MigratedPromptFile,
): ResultAsync<void, { message: string }> {
  const path = resolve(promptsDir, promptFile.path);
  const content = `${promptFile.content}\n`;
  return fs
    .exists(path)
    .mapErr(fsError)
    .andThen((exists) =>
      exists
        ? fs.readText(path).mapErr(fsError)
        : okAsync<string | undefined, { message: string }>(undefined),
    )
    .andThen((existing) => {
      if (existing === content) return okAsync(undefined);
      const backup =
        existing === undefined
          ? okAsync<void, { message: string }>(undefined)
          : fs.copyFile(path, `${path}.bak`).mapErr(fsError);
      return backup.andThen(() => fs.writeText(path, content).mapErr(fsError));
    });
}

function writePromptFiles(
  fs: FileSystem,
  plan: MigrationPlan,
  promptFiles: readonly MigratedPromptFile[],
): ResultAsync<void, { message: string }> {
  if (promptFiles.length === 0) return okAsync(undefined);
  const promptsDir = resolve(plan.destinationDir, "prompts");
  return promptFiles.reduce(
    (previous, promptFile) =>
      previous.andThen(() => writePromptFile(fs, promptsDir, promptFile)),
    fs.mkdir(promptsDir).mapErr(fsError),
  );
}

/**
 * Write pre-built DSL content to the migration destination, with validation
 * before any file mutation.
 *
 * Exported for direct testing of the validation gate: callers can inject
 * arbitrary DSL (including intentionally invalid DSL) to verify that the
 * `parseConfig()` check fires before any destination or backup file is touched.
 *
 * Sequence:
 *   1. Validate `dslContent` through `parseConfig()` — abort with `errAsync` if invalid.
 *   2. If `destExists`, copy destination → `<destination>.bak`.
 *   3. `mkdir` the destination directory.
 *   4. Write migrated prompt files into `<destination dir>/prompts/`.
 *   5. Write `dslContent` to the destination path.
 *
 * On any failure the function returns `errAsync` and leaves the filesystem in
 * whatever state it was before the failing step (backup copy is atomic at the
 * MemoryFileSystem level; real FS callers should treat this as best-effort).
 */
export function writeMigratedDsl(
  fs: FileSystem,
  plan: MigrationPlan,
  dslContent: string,
  destExists: boolean,
  promptFiles: readonly MigratedPromptFile[] = [],
): ResultAsync<{ backedUp: boolean }, { message: string }> {
  const validationResult = parseConfig(dslContent);
  if (validationResult.isErr()) {
    const errorSummary = validationResult.error
      .map((e) => ("message" in e ? e.message : JSON.stringify(e)))
      .join("; ");
    return errAsync({
      message: `Generated DSL failed validation: ${errorSummary}`,
    });
  }

  const backup = destExists
    ? fs.copyFile(plan.destinationPath, `${plan.destinationPath}.bak`)
    : ResultAsync.fromSafePromise(Promise.resolve());

  return backup
    .mapErr(fsError)
    .andThen(() => fs.mkdir(plan.destinationDir).mapErr(fsError))
    .andThen(() => writePromptFiles(fs, plan, promptFiles))
    .andThen(() =>
      fs.writeText(plan.destinationPath, dslContent).mapErr(fsError),
    )
    .map(() => ({ backedUp: destExists }));
}

// ---------------------------------------------------------------------------
// Full migration write (convert + write)
// ---------------------------------------------------------------------------

/**
 * Convert legacy JSONC source content (unless an already-successful
 * `preConversion` is supplied) and write the result to the migration
 * destination. Validation runs before any file mutation, and a conversion
 * that failed outright writes nothing.
 *
 * Returns the backup status, any conversion warnings, and the prompt files
 * that were carried over on success.
 */
export function performMigrationWrite(
  fs: FileSystem,
  plan: MigrationPlan,
  sourceContent: string,
  destExists: boolean,
  preConversion?: ConversionResult,
): ResultAsync<
  {
    backedUp: boolean;
    warnings: ConversionWarning[];
    promptFiles: MigratedPromptFile[];
  },
  { message: string }
> {
  const conversion =
    preConversion !== undefined
      ? okAsync<ConversionResult, { message: string }>(preConversion)
      : convertLegacySource(fs, plan.sourcePath, sourceContent).mapErr(
          (error) => ({ message: describeFailedConversion(error) }),
        );
  return conversion.andThen((converted) => {
    const promptFiles = converted.promptFiles ?? [];
    return writeMigratedDsl(
      fs,
      plan,
      buildMigratedContent(plan, converted),
      destExists,
      promptFiles,
    ).map((result) => ({
      ...result,
      warnings: converted.warnings,
      promptFiles,
    }));
  });
}
