/**
 * Migration write orchestration.
 *
 * Handles the read-check-write-validate sequence for migrating a legacy
 * JSONC config to a new DSL config file. Validation runs before any file
 * mutation so that invalid generated DSL cannot corrupt the destination.
 */

import { parseConfig } from "@weave/core";
import { errAsync, ResultAsync } from "neverthrow";
import { starterConfig } from "../config/starter-config.js";
import { describeFileSystemError, type FileSystem } from "../fs/file-system.js";
import { convertLegacyJsonc } from "./legacy-jsonc-converter.js";
import type {
  ConversionResult,
  ConversionWarning,
  MigrationPlan,
} from "./types.js";

// ---------------------------------------------------------------------------
// DSL content builder
// ---------------------------------------------------------------------------

/**
 * Build migrated config.weave content with a provenance comment.
 * Incorporates converted DSL from the JSONC conversion result.
 * Falls back to starter config body when conversion produces no DSL.
 */
export function buildMigratedContent(
  plan: MigrationPlan,
  conversion: ConversionResult,
): string {
  const provenanceComment = [
    `# Migrated from legacy OpenCode JSONC config`,
    `# Source: ${plan.sourcePath}`,
    `# Scope: ${plan.scope}`,
    `# Generated by: weave init migrate`,
    "",
  ].join("\n");

  const body =
    conversion.dsl.trim().length > 0
      ? conversion.dsl + "\n"
      : starterConfig(plan.scope);

  return provenanceComment + body;
}

// ---------------------------------------------------------------------------
// Write with validation gate
// ---------------------------------------------------------------------------

/**
 * Write pre-built DSL content to the migration destination, with validation
 * before any file mutation.
 *
 * Exported for direct testing of the validation gate: callers can inject
 * arbitrary DSL (including intentionally invalid DSL) to verify that the
 * `parseConfig()` check fires before any destination or backup file is touched.
 *
 * Sequence:
 *   1. Validate `dslContent` through `parseConfig()` — abort with `errAsync` if invalid.
 *   2. If `destExists`, copy destination → `<destination>.bak`.
 *   3. `mkdir` the destination directory.
 *   4. Write `dslContent` to the destination path.
 *
 * On any failure the function returns `errAsync` and leaves the filesystem in
 * whatever state it was before the failing step (backup copy is atomic at the
 * MemoryFileSystem level; real FS callers should treat this as best-effort).
 */
export function writeMigratedDsl(
  fs: FileSystem,
  plan: MigrationPlan,
  dslContent: string,
  destExists: boolean,
): ResultAsync<{ backedUp: boolean }, { message: string }> {
  const validationResult = parseConfig(dslContent);
  if (validationResult.isErr()) {
    const errorSummary = validationResult.error
      .map((e) => ("message" in e ? e.message : JSON.stringify(e)))
      .join("; ");
    return errAsync({
      message: `Generated DSL failed validation: ${errorSummary}`,
    });
  }

  const backup = destExists
    ? fs.copyFile(plan.destinationPath, `${plan.destinationPath}.bak`)
    : ResultAsync.fromSafePromise(Promise.resolve());

  return backup
    .mapErr((error) => ({ message: describeFileSystemError(error) }))
    .andThen(() =>
      fs
        .mkdir(plan.destinationDir)
        .mapErr((error) => ({ message: describeFileSystemError(error) })),
    )
    .andThen(() =>
      fs
        .writeText(plan.destinationPath, dslContent)
        .mapErr((error) => ({ message: describeFileSystemError(error) })),
    )
    .map(() => ({ backedUp: destExists }));
}

// ---------------------------------------------------------------------------
// Full migration write (convert + write)
// ---------------------------------------------------------------------------

/**
 * Convert legacy JSONC source content and write the result to the migration
 * destination. Validation runs before any file mutation.
 *
 * Returns the backup status and any conversion warnings on success.
 */
export function performMigrationWrite(
  fs: FileSystem,
  plan: MigrationPlan,
  sourceContent: string,
  destExists: boolean,
  preConversion?: ConversionResult,
): ResultAsync<
  { backedUp: boolean; warnings: ConversionWarning[] },
  { message: string }
> {
  const conversion = preConversion ?? convertLegacyJsonc(sourceContent);
  const migratedContent = buildMigratedContent(plan, conversion);
  return writeMigratedDsl(fs, plan, migratedContent, destExists).map(
    (result) => ({ ...result, warnings: conversion.warnings }),
  );
}
