export type {
  CreatePiAdapterCommandHandlersOptions,
  PiAdapterChildEntrySummary,
  PiAdapterChildListItem,
  PiAdapterChildrenPort,
  PiAdapterCommandPortError,
  PiAdapterDoctorPort,
  PiChildResultPage,
  PiChildrenCommandPortOptions,
  PiChildrenDeleteResult,
  PiChildrenListResult,
  PiChildrenResolveResult,
  PiChildrenResultResult,
  PiChildrenShowResult,
  PiDoctorResult,
} from "./adapter-cli-commands.js";
export {
  createPiAdapterCommandHandlers,
  createPiAdapterCommandRegistry,
  createPiChildrenCommandPort,
  createPlaceholderDoctorPort,
  decodeResultPageBase64,
  encodeResultPageBase64,
  looksLikeFilesystemPath,
  PI_ADAPTER_COMMAND_BOUNDS,
  PI_ADAPTER_COMMAND_NAMES,
  PI_ADAPTER_NAME,
  PI_RESULT_CONTENT_ENCODING,
  PiChildrenDeleteResultSchema,
  PiChildrenListResultSchema,
  PiChildrenResolveResultSchema,
  PiChildrenResultResultSchema,
  PiChildrenShowResultSchema,
  PiDoctorResultSchema,
  stripPathsUnlessDiagnostic,
} from "./adapter-cli-commands.js";
export type {
  CreateProductionPiAdapterCommandPortsOptions,
  PiProductionAdapterAccessMode,
  PiProductionAdapterCliOpenError,
  PiProductionAdapterCommandError,
  PiProductionAdapterCommandPorts,
  ResolveProductionAdapterCliRegistryInput,
} from "./adapter-cli-production.js";
export {
  accessModeForAdapterAction,
  createProductionPiAdapterCommandRegistry,
  createProductionPorts,
  evaluateProductionChildrenDeleteGate,
  openProductionPiAdapterCommandPorts,
  resolveProductionAdapterCliRegistry,
} from "./adapter-cli-production.js";
export type {
  PiSanitizedChildIndex,
  PiSanitizedChildIndexEntry,
  PiSanitizedChildIndexError,
  PiSanitizedChildIndexInput,
} from "./artifact-provider.js";
export {
  createPiSanitizedChildIndex,
  MAX_SANITIZED_CHILD_EXPORT_BYTES,
  MAX_SANITIZED_CHILD_INDEX_ENTRIES,
  PiSanitizedChildIndexEntrySchema,
  PiSanitizedChildIndexExporter,
  PiSanitizedChildIndexSchema,
} from "./artifact-provider.js";
export {
  PI_ADAPTER_CAPABILITY_CONTRACT,
  PI_HOST_SURFACE_DECLARATIONS,
  type PiHostSurfaceDeclaration,
} from "./capability-declarations.js";
export type {
  PiCandidatePlanContext,
  PiCapabilityProbeSource,
  PiPreflightContext,
} from "./capability-prober.js";
export {
  buildBlockedProbeSet,
  DefaultPiCapabilityProber,
  PROJECT_PATH_DEPENDENT_CAPABILITIES,
  sanitizeCapabilityProbeResults,
} from "./capability-prober.js";
export type {
  ChildCompactDegradedReason,
  ChildCompactError,
  ChildCompactItem,
  ChildCompactItemKind,
  ChildCompactReducerInput,
  ChildCompactRenderOptions,
  ChildCompactRenderOutput,
  ChildCompactRunAction,
  ChildCompactRunBlock,
  ChildCompactRunStatus,
  ChildCompactState,
} from "./child-compact-render.js";
export {
  boundChildCompactId,
  CHILD_COMPACT_COLLAPSED_CODE_POINTS,
  CHILD_COMPACT_EXPANDED_CODE_POINTS,
  CHILD_COMPACT_MAX_DEDUP_KEYS,
  CHILD_COMPACT_MAX_ITEMS,
  CHILD_COMPACT_MAX_RUNS,
  childCompactLineCount,
  createChildCompactState,
  degradedChildCompactRender,
  mapPiChildSessionEventToCompactInput,
  parseReducerInput,
  projectChildCompact,
  reduceChildCompact,
  reduceChildCompactSafe,
  renderChildCompact,
  renderChildCompactSafe,
  sanitizeChildCompactText,
} from "./child-compact-render.js";
export {
  type ErasableSecret as PiErasableSecret,
  generateChildSecret,
  generateNonceHex,
  type HmacPort as PiHmacPort,
  type RandomPort as PiRandomPort,
  WebCryptoHmacPort,
  WebCryptoRandomPort,
} from "./child-crypto.js";
export type {
  PiDoctorCheck,
  PiDoctorCheckFailure,
  PiDoctorCheckId,
  PiDoctorCheckOutcome,
  PiDoctorCheckPorts,
  PiDoctorOrphanScanInput,
  RunChildDoctorInput,
} from "./child-doctor.js";
export {
  createPiDoctorPort,
  createSkippedDoctorCheckPorts,
  createStoreBackedDoctorCheckPorts,
  doctorCapabilitiesFromProbes,
  doctorOrphanCheckFromRows,
  doctorStaleCheckFromRows,
  failedDoctorCheck,
  PI_DOCTOR_BOUNDS,
  PI_DOCTOR_CHECK_IDS,
  PiDoctorCheckIdSchema,
  PiDoctorCheckSchema,
  passedDoctorCheck,
  runChildDoctor,
  skippedDoctorCheck,
} from "./child-doctor.js";
export {
  PiChildAuthState,
  type PiControlDirection,
  type PiControlEnvelope,
  type PiControlKind,
  signEnvelope,
  verifyEnvelope,
} from "./child-envelope.js";
export {
  type FramingError as PiFramingError,
  PiLineFramer,
} from "./child-framing.js";
export type {
  PiChildInspectionEditorHost,
  PiChildInspectionEditorResult,
} from "./child-inspection-editor.js";
export {
  createChildInspectionEditor,
  PiChildInspectionEditor,
} from "./child-inspection-editor.js";
export type {
  InspectionBreadcrumbSegment,
  InspectionCacheKey,
  InspectionSummary,
  InspectionWorkflowMeta,
  PiChildInspectionRenderError,
  PiChildInspectionRenderInput,
  PiChildInspectionRenderOutput,
} from "./child-inspection-render.js";
export {
  createChildInspectionRenderer,
  PiChildInspectionRenderer,
  renderChildInspection,
} from "./child-inspection-render.js";
export type {
  PiChildInspectionEditorCell,
  PiChildInspectionParentSession,
  PiChildInspectionRegistryCell,
  PiChildInspectionRuntime,
  PiChildInspectionRuntimeDeps,
  PiChildOverlayCell,
  PiChildOverlayKeysCell,
  PiChildTreeSelectionCell,
  PiDelegationControllerCell,
  PiThreadSourcesCell,
} from "./child-inspection-runtime.js";
export {
  clearChildOverlayGeneration,
  clearThreadSources,
  closeChildOverlay,
  createChildInspectionEditorCell,
  createChildInspectionRegistryCell,
  createChildInspectionRuntime,
  createChildOverlayCell,
  createChildOverlayKeysCell,
  createChildTreeSelectionCell,
  createDelegationControllerCell,
  createThreadSourcesCell,
} from "./child-inspection-runtime.js";
export type {
  PiChildInspectionEffectiveSettings,
  PiChildInspectionSettings,
  PiChildInspectionSettingsChoice,
  PiChildInspectionSettingsIssue,
  PiChildInspectionSettingsMode,
  PiChildInspectionSettingsResolution,
} from "./child-inspection-settings.js";
export {
  childInspectionOverlayKeyOverrides,
  DEFAULT_PI_CHILD_INSPECTION_SETTINGS,
  effectivePiChildInspectionSettings,
  formatPiChildInspectionSettingsIssues,
  PiChildInspectionSettingsSchema,
  parsePiChildInspectionSettings,
  resolvePiChildInspectionSettings,
} from "./child-inspection-settings.js";
export type {
  PiChildSlashCommand,
  PiInspectorChild,
  PiInspectorConfirmation,
  PiInspectorError,
  PiInspectorRpc,
  PiInspectorStatus,
  PiInspectorView,
  PiInspectorViewState,
  PiInspectorViewStateUpdate,
} from "./child-inspector.js";
export {
  EMPTY_INSPECTOR_VIEW_STATE,
  interceptChildSlashCommand,
  PiChildInspector,
  PiChildSlots,
} from "./child-inspector.js";
export type {
  PiChildMetadataBypass,
  PiChildMetadataCacheDegradeReason,
  PiChildMetadataCacheError,
  PiChildMetadataCacheFileProbe,
  PiChildMetadataCacheFsError,
  PiChildMetadataCacheFsPort,
  PiChildMetadataCacheOpenOptions,
  PiChildMetadataCacheOpenOutcome,
  PiChildMetadataCacheRootViolation,
  PiChildMetadataDatabase,
  PiChildMetadataDatabaseOpener,
  PiChildMetadataListInput,
  PiChildMetadataPage,
  PiChildMetadataRebuildReport,
  PiChildMetadataRecord,
  PiChildMetadataScope,
  PiChildMetadataSource,
} from "./child-metadata-cache.js";
export {
  BunPiChildMetadataCacheFs,
  childMetadataRecordFromRef,
  createChildMetadataBypass,
  FakePiChildMetadataCacheFs,
  openBunChildMetadataDatabase,
  openBunChildMetadataDatabaseReadOnly,
  openPiChildMetadataCache,
  openPiChildMetadataCacheReadOnly,
  PI_CHILD_METADATA_CACHE_BOUNDS,
  PI_CHILD_METADATA_CACHE_COLUMNS,
  PI_CHILD_METADATA_CACHE_LAYOUT,
  PI_CHILD_METADATA_CACHE_SCHEMA_VERSION,
  PI_CHILD_METADATA_FORBIDDEN_COLUMN_TOKENS,
  PiChildMetadataCache,
  parseChildMetadataRecord,
  READ_ONLY_WRITE_REFUSED,
  resolvePiChildMetadataCacheRoot,
} from "./child-metadata-cache.js";
export type {
  PiChildCardComponentOptions,
  PiNativeTranscriptComponentDeps,
} from "./child-native-components.js";
export {
  CHILD_CARD_NATIVE_RENDER_FAILED,
  CHILD_COMPACT_NATIVE_RENDER_FAILED,
  createPiNativeTranscriptComponentFactory,
  degradedPiChildCardComponent,
  renderPiChildCardComponent,
  renderPiChildCompactComponent,
} from "./child-native-components.js";
export type {
  CreateNativeChildSessionInput,
  PiNativeResultAppendIdentity,
  PiNativeResultChunk,
  PiNativeResultCommit,
  PiNativeResultCommitIdentity,
  PiNativeResultGroupAcceptance,
  PiNativeResultGroupIncompleteReason,
  PiNativeResultGroupRead,
  PiNativeResultGroupReadOptions,
  PiNativeResultGroupState,
  PiNativeResultGroupSummary,
  PiNativeResultIdentity,
  PiNativeResultLeafIdentity,
  PiNativeResultReadIdentity,
  PiNativeSessionCorruption,
  PiNativeSessionDeletionPhase,
  PiNativeSessionDeletionRecord,
  PiNativeSessionDirectory,
  PiNativeSessionEntries,
  PiNativeSessionEntryCursor,
  PiNativeSessionEntryPage,
  PiNativeSessionEntryPageDirection,
  PiNativeSessionEntryPageOptions,
  PiNativeSessionError,
  PiNativeSessionFileRange,
  PiNativeSessionFileStat,
  PiNativeSessionFsError,
  PiNativeSessionFsPort,
  PiNativeSessionGrantRefusal,
  PiNativeSessionHandle,
  PiNativeSessionHeader,
  PiNativeSessionHostPort,
  PiNativeSessionPagedEntry,
  PiNativeSessionRecord,
  PiNativeSessionRootViolation,
  PiNativeSessionState,
  PiNativeSessionStorageUnavailable,
  PiNativeSessionStoreLaunchMode,
  PiNativeSessionStoreOptions,
  PiNativeSessionTombstone,
  PiNativeThreadMetadata,
  PiNativeThreadMetadataInput,
} from "./child-native-sessions.js";
export {
  decodePiNativeSessionEntryCursor,
  encodePiNativeSessionEntryCursor,
  isDisjointFromDefaultSessionTree,
  nativeSessionDeletionToken,
  PI_NATIVE_RESULT_CHUNK_ENTRY_TYPE,
  PI_NATIVE_RESULT_COMMIT_ENTRY_TYPE,
  PI_NATIVE_RESULT_GROUP_BOUNDS,
  PI_NATIVE_RESULT_SCHEMA_VERSION,
  PI_NATIVE_SESSION_ENTRY_CURSOR_VERSION,
  PI_NATIVE_SESSION_ENTRY_PAGE_BOUNDS,
  PI_NATIVE_SESSION_LAYOUT,
  PI_NATIVE_SESSION_MAX_RANGE_LENGTH,
  PI_NATIVE_THREAD_ENTRY_TYPE,
  PI_NATIVE_THREAD_SCHEMA_VERSION,
  PiNativeResultChunkSchema,
  PiNativeResultCommitSchema,
  PiNativeSessionEntryCursorSchema,
  PiNativeSessionStore,
  PiNativeThreadMetadataSchema,
  readNativeResultGroup,
  readNativeThreadMetadata,
  resolvePiNativeSessionRoot,
  safeNativeSessionComponent,
  setPiNativeSessionMaxRangeLengthForTests,
  verifyNativeSessionRef,
} from "./child-native-sessions.js";
export type {
  ChildOverlayAnchor,
  ChildOverlayChild,
  ChildOverlayConfig,
  ChildOverlayDescriptorUsage,
  ChildOverlayEntry,
  ChildOverlayEntryKind,
  ChildOverlayError,
  ChildOverlayFallbackMetadata,
  ChildOverlayFallbackReason,
  ChildOverlayFallbackRequired,
  ChildOverlayIdentity,
  ChildOverlayInputOutcome,
  ChildOverlayMappingError,
  ChildOverlayMutationPort,
  ChildOverlayPage,
  ChildOverlayPlanContext,
  ChildOverlayPlanContextPort,
  ChildOverlayReplayStep,
  ChildOverlayRunDivider,
  ChildOverlaySourceError,
  ChildOverlaySourceErrorType,
  ChildOverlaySourcePort,
  ChildOverlayStatus,
  ChildOverlayTelemetry,
  ChildOverlayView,
  MemoryOverlaySourceChild,
  MemoryOverlaySourceEntry,
  PiChildOverlayCustomComponent,
} from "./child-overlay.js";
export {
  CHILD_OVERLAY_BOUNDS,
  CHILD_OVERLAY_TELEMETRY_BOUNDS,
  ChildOverlayChildSchema,
  ChildOverlayController,
  ChildOverlayRunDividerSchema,
  ChildOverlayStatusSchema,
  createChildOverlayController,
  createChildOverlayCustomComponent,
  createMemoryChildOverlaySource,
  createReadSessionEntryPageOverlaySource,
  mapNativeSessionEntryPageToOverlay,
  mapNativeSessionEntryToOverlay,
  mapPiDelegationFailureToOverlaySourceError,
  mergeChildOverlayReplaySteps,
  transcriptFromOverlayEntries,
} from "./child-overlay.js";
export type {
  PiChildOverlayAction,
  PiChildOverlayActionDefinition,
  PiChildOverlayActionId,
  PiChildOverlayCancelDecision,
  PiChildOverlayHierarchyNode,
  PiChildOverlayKey,
  PiChildOverlayKeybindingConflictPort,
  PiChildOverlayKeyConflict,
  PiChildOverlayKeyContext,
  PiChildOverlayKeyError,
  PiChildOverlayKeyInterceptor,
  PiChildOverlayKeyMachineDeps,
  PiChildOverlayKeyOutcome,
  PiChildOverlayKeyOverrides,
  PiChildOverlayKeyPlan,
  PiChildOverlayKeyPlanInput,
  PiChildOverlayKeyRegistration,
  PiChildOverlayShortcutRegistrar,
  PiChildOverlaySlotActionId,
  PiKeybindingsConfigPort,
} from "./child-overlay-keys.js";
export {
  applyChildOverlayKeyPlan,
  CHILD_OVERLAY_CANCEL_CHOICES,
  CHILD_OVERLAY_CANCEL_DEFAULT_CHOICE,
  CHILD_OVERLAY_CANCEL_PROMPT,
  captureChildOverlayKeybindings,
  childOverlayActionFromId,
  childOverlayActiveSlots,
  childOverlayConflictPortFromHost,
  childOverlayParent,
  childOverlaySibling,
  childOverlayTreeOrder,
  classifyChildOverlayKey,
  createChildOverlayConflictPort,
  createChildOverlayKeyInterceptor,
  createChildOverlayKeyMachine,
  isChildOverlaySearchOpenInput,
  isPiChildOverlayActionId,
  PI_CHILD_OVERLAY_ACTION_IDS,
  PI_CHILD_OVERLAY_ACTIONS,
  PI_CHILD_OVERLAY_KEY_BOUNDS,
  PI_CHILD_OVERLAY_SEARCH_KEY,
  PI_CHILD_OVERLAY_SEARCH_KEY_USUAL_OWNER,
  PI_CHILD_OVERLAY_SEARCH_OPEN_KEY,
  PI_CHILD_OVERLAY_SEARCH_TRIGGER,
  PI_CHILD_OVERLAY_UNCLAIMED_KEYS_NOTE,
  PI_NAMED_SHORTCUT_ACTIONS_CAPABILITY_ID,
  PI_NAMED_SHORTCUT_ACTIONS_DIAGNOSTIC,
  PiChildOverlayKeyMachine,
  parseChildOverlayKeyOverrides,
  planChildOverlayKeyRegistrations,
  resolveChildOverlayCancelChoice,
  resolveChildOverlaySearchRoute,
} from "./child-overlay-keys.js";
export type {
  PiChildPickerActiveChild,
  PiChildPickerCachePort,
  PiChildPickerCacheRecord,
  PiChildPickerCandidate,
  PiChildPickerCandidateInput,
  PiChildPickerEntry,
  PiChildPickerError,
  PiChildPickerInput,
  PiChildPickerKind,
  PiChildPickerMetadataEntry,
  PiChildPickerMetadataInput,
  PiChildPickerNode,
  PiChildPickerRefPort,
  PiChildPickerRefRecord,
  PiChildPickerSourceState,
  PiChildPickerState,
  PiChildPickerStatus,
} from "./child-picker.js";
export {
  buildChildPickerEntries,
  buildChildPickerMetadataEntries,
  collectChildPickerCandidates,
  createChildPickerEntries,
  createChildPickerMetadataEntries,
  moveChildPicker,
  PI_CHILD_PICKER_BOUNDS,
  PI_CHILD_PICKER_STATUSES,
  resolveChildPickerTitle,
  sanitizeChildPickerPreview,
  selectedChildPickerEntry,
} from "./child-picker.js";
export {
  BunPiChildProcessPort,
  type ChildProcessError as PiChildProcessError,
  type PiChildProcessPort,
  type PiChildSpawnInput,
  type PiSpawnedChildProcess,
} from "./child-process-port.js";
export type {
  PiChildErrorClass,
  PiChildErrorMessage,
  PiChildProviderError,
  PiChildProviderErrorAbsence,
  PiChildProviderErrorDescriptor,
  PiChildSafeErrorCode,
} from "./child-provider-error.js";
export {
  CHILD_ERROR_CANONICAL_MESSAGE,
  CHILD_PROVIDER_ERROR_BOUNDS,
  MAX_CHILD_ERROR_MESSAGE_LENGTH,
  PI_CHILD_ERROR_CLASSES,
  PI_CHILD_ERROR_MESSAGES,
  PiChildProviderErrorSchema,
} from "./child-provider-error.js";
// Narrow public surface: the read-only model Task 13 renders. Ingestion of
// unknown input, event parsing, and replay-field plumbing stay internal to the
// adapter, so no external caller can feed arbitrary values into the projection.
export { formatPiChildProviderError } from "./child-provider-error-render.js";
export {
  authorizeChildAccess,
  classifyChildAccess,
  type PiChildAccessDenial,
  type PiChildAccessOperation,
  type PiChildAccessState,
  type PiChildBootstrapHandlers,
  type PiChildOutputPort,
  PiChildRuntime,
  type PiChildRuntimeDeps,
} from "./child-runtime.js";
export type {
  PiChildCheckpointError,
  PiChildSessionCheckpoint,
  PiChildSessionCheckpointEntry,
} from "./child-session-checkpoint.js";
export {
  appendUnseenCheckpointEntries,
  createEmptyPiChildSessionCheckpoint,
  decodePiChildSessionCheckpoint,
  encodePiChildSessionCheckpoint,
  MAX_CHECKPOINT_BYTES,
  PiChildSessionCheckpointSchema,
  parsePiChildSessionCheckpoint,
} from "./child-session-checkpoint.js";
export type {
  PiChildEventType,
  PiChildSessionEvent,
  PiExtensionUiResponse,
} from "./child-session-events.js";
export {
  PiChildSessionEventSchema,
  PiExtensionUiResponseSchema,
  parsePiChildSessionEvent,
  preserveUnknownChildEvent,
} from "./child-session-events.js";
export type {
  AppendChildRefLifecycleInput,
  AppendChildRefRunInput,
  AppendNewChildRefInput,
  PiChildRefAppendPort,
  PiChildRefEntryKind,
  PiChildRefEntryReadPort,
  PiChildRefError,
  PiChildRefIssue,
  PiChildRefNativeSessionReader,
  PiChildRefRecord,
  PiChildRefRun,
  PiChildRefRunAction,
  PiChildRefScan,
  PiChildRefScanCounts,
  PiChildRefSourceAuthority,
  PiChildRefSourceState,
  PiChildRefStatus,
  PiChildSessionRefStoreOptions,
} from "./child-session-refs.js";
export {
  createNativeChildRefSourceAuthority,
  hasNoTranscriptFields,
  PI_CHILD_REF_BOUNDS,
  PI_CHILD_REF_ENTRY_TYPE,
  PI_CHILD_REF_FORBIDDEN_FIELDS,
  PI_CHILD_REF_SCHEMA_VERSION,
  PiChildSessionRefStore,
  parseChildRefEnvelope,
  parseChildRefRecord,
  serializeChildRefEnvelope,
} from "./child-session-refs.js";
export {
  CHILD_SESSION_STORAGE_UNAVAILABLE_REASON,
  createPiChildSessionStorageAuthority,
  describeChildSessionStorageUnavailable,
  type PiChildSessionRootProof,
  type PiChildSessionStorageAuthority,
  provePiChildSessionRoot,
} from "./child-session-storage-authority.js";
export {
  DEFAULT_HANDSHAKE_TIMEOUT_MS,
  DEFAULT_REPLY_TIMEOUT_MS,
  DEFAULT_SETTLEMENT_TIMEOUT_MS,
  SystemTimerPort,
  type TimerHandle,
  type TimerPort,
} from "./child-timer.js";
export type {
  PiChildTitleProvenance,
  PiDurableChildTitleInput,
  PiStoredChildTitle,
} from "./child-title.js";
export {
  durableChildTitleSuffix,
  enforceDurableChildTitle,
  enforceDurableChildTitleProvenance,
  isProvenDurableChildTitle,
  isTrustedChildTitleProvenance,
  PI_CHILD_TITLE_BOUNDS,
  PI_CHILD_TITLE_FALLBACK_LABEL,
  PI_CHILD_TITLE_PROVENANCE,
  PI_CHILD_TITLE_PROVENANCE_VALUES,
  resolveDurableChildTitle,
} from "./child-title.js";
export {
  addUsage,
  applyTreeControlKey,
  EMPTY_USAGE_AGGREGATE,
  MAX_LATEST_OUTPUT_BYTES,
  type PiChildStatus,
  type PiChildTreeNode,
  type PiChildUsageAggregate,
  type PiTreeControlKey,
  type PiTreeControlOutcome,
  ROOT_NODE_ID,
  subtreeIds,
  truncateLatestOutput,
} from "./child-tree.js";
export type {
  WeaveCommandClassification,
  WeaveCommandName,
} from "./commands.js";
export {
  ADAPTER_PACKAGE_IDENTITY,
  classifyWeaveCommand,
  isOwnSourceInfo,
  parseNpmSourceName,
  WEAVE_CLEAR_CHILDREN_COMMAND_NAME,
  WEAVE_COMMAND_CLASSIFICATIONS,
  WEAVE_COMMAND_NAMES,
  WEAVE_DOCTOR_COMMAND_NAME,
  WEAVE_HISTORY_COMMAND_NAME,
  WEAVE_INSPECT_COMMAND_NAME,
  WEAVE_RECOVERY_COMMAND_NAME,
} from "./commands.js";
export type {
  PiConfigActivationInput,
  PiConfigActivationResult,
  PiConfigActivatorDeps,
  PiConfigLoaderPort,
  PiDescriptorCatalog,
  PiMaterializerPort,
} from "./config-activator.js";
export {
  buildDescriptorCatalog,
  createTrustWithheldFileReader,
  defaultPiConfigLoaderPort,
  defaultPiFileReader,
  defaultPiMaterializerPort,
  logMaterializationErrors,
  PiConfigActivator,
} from "./config-activator.js";
export type {
  PiCommandGateDecision,
  PiExtensionControllerDeps,
  PiGeneration,
  PiOperationHandle,
} from "./controller.js";
export { PiExtensionController } from "./controller.js";
export {
  DEFAULT_THREAD_RETRY_INSTRUCTION,
  PiDelegationController,
  type PiDelegationControllerDeps,
  type PiDelegationRequest,
  type PiOverlayChildDescriptor,
  type PiOverlayChildUsage,
  type PiThreadAction,
  type PiThreadCachePort,
  type PiThreadInitiator,
  type PiThreadRefPort,
  type PiThreadRunAssignment,
  type PiThreadRunOutcome,
  type PiThreadRunRequest,
  type PiThreadSessionPort,
} from "./delegation-controller.js";
export {
  buildDelegationToolRegistration,
  CARD_DETAILS_INVALID_CODE,
  CARD_REFRESH_INTERVAL_MS,
  CARD_RENDER_FAILED_CODE,
  DELEGATION_CARD_DETAILS_VERSION,
  MAX_DELEGATION_CARD_DETAILS_BYTES,
  PiCardUpdateCoalescer,
  type PiCardUpdatePriority,
  type PiDelegationCardDetails,
  type PiDelegationCardDetailsError,
  PiDelegationCardStream,
  type PiDelegationCardStreamConfig,
  type PiDelegationToolDeps,
  parseDelegationCardDetails,
  renderDelegationCardResult,
  WEAVE_DELEGATION_TOOL_NAME,
} from "./delegation-tool.js";
export type {
  PiAdapterFailure,
  PiAdapterFailureCode,
  PiAdapterFailureImpact,
  PiAdapterFailurePhase,
  PiAdapterFailureRecovery,
  PiAdapterFailureScope,
  PiDiagnosticCode,
} from "./errors.js";
export {
  makeActivationFailedFailure,
  makeChildCheckpointInvalidFailure,
  makeChildControlEnvelopeTooLargeFailure,
  makeChildExtensionUiRejectedFailure,
  makeChildInteractionUnavailableFailure,
  makeChildNativeRecordTooLargeFailure,
  makeChildOrphanReadOnlyFailure,
  makeChildRecordCorruptFailure,
  makeChildRecordQuarantinedFailure,
  makeChildRecordQuotaExceededFailure,
  makeChildRecoveryUnavailableFailure,
  makeChildSchemaInvalidFailure,
  makeCommandCollisionFailure,
  makeControllerGenerationStaleFailure,
  makeHostIdentityUnknownFailure,
  makeHostVersionUnsupportedFailure,
  makeInteractiveTuiRequiredFailure,
  makeInvariantViolationFailure,
  makePersistentParentSessionRequiredFailure,
  makeRequiredCapabilityUnavailableFailure,
  makeUiBridgeUnavailableFailure,
  PiAdapterFailureCodeSchema,
  PiAdapterFailureImpactSchema,
  PiAdapterFailurePhaseSchema,
  PiAdapterFailureRecoverySchema,
  PiDiagnosticCodeSchema,
} from "./errors.js";
export type { PiExtensionDeps } from "./extension.js";
export {
  createDefaultPiExtensionDeps,
  createPiExtension,
} from "./extension.js";
export type {
  HostPackageInfo,
  HostPackageReader,
} from "./host-compatibility.js";
export {
  BunHostPackageReader,
  checkHostCompatibility,
  HOST_PACKAGE_NAME,
  HOST_VERSION_FLOOR,
  HostPackageInfoSchema,
  isSupportedHostVersion,
  parseSemver,
} from "./host-compatibility.js";
export type {
  HostCompatibilityMatrixError,
  PiHostCompatibilityMatrix,
} from "./host-compatibility-matrix.js";
export {
  PI_HOST_COMPATIBILITY_MATRIX,
  validateHostCompatibilityMatrix,
} from "./host-compatibility-matrix.js";
export {
  buildHostSurfaceGapDiagnostics,
  createDefaultPiHostProbePort,
  DefaultPiHostSurfaceReader,
  defaultHostSurfaceReport,
  emptyHostSurfaceReport,
  PI_HOST_SURFACE_IDS,
  type PiHostProbePort,
  type PiHostProbePortFactory,
  type PiHostSurfaceId,
  type PiHostSurfaceProbe,
  type PiHostSurfaceReadError,
  type PiHostSurfaceReader,
  type PiHostSurfaceReadInput,
  type PiHostSurfaceReport,
  type PiHostSurfaceStatus,
  readHostSurfaceReport,
  readValidatedCommands,
  safeReadHostSurfaceReport,
  selectsCustomEditorFallback,
} from "./host-inventory.js";
export type {
  PiModelActivationOutcome,
  PiModelApplyPort,
  PiModelInfo,
  PiModelResolution,
  PiModelResolutionSource,
  PiThinkingApplyPort,
} from "./model-resolution.js";
export { PiModelActivator, PiModelResolver } from "./model-resolution.js";
export {
  BunPiNativeSessionFs,
  createBunPiNativeSessionFs,
  MemoryPiNativeSessionFs,
} from "./native-session-fs.js";
export type {
  PiNativeSessionHeaderViolation,
  PiValidatedSessionHeader,
} from "./native-session-header.js";
export { validatePiNativeSessionHeader } from "./native-session-header.js";
export type {
  PiSessionManagerInstance,
  PiSessionManagerStatic,
} from "./native-session-host.js";
export {
  adaptPiSessionManagerHandle,
  createPiNativeSessionHost,
  isPiSessionManagerStatic,
} from "./native-session-host.js";
export type {
  PiActivePrimary,
  PiParentMutationOperation,
  PiParentSessionProbePort,
  PiParentSessionState,
  PiPrimaryActivationContext,
  PiPrimaryActivationError,
  PiPrimaryCapabilityWarning,
  PiPrimaryFastIntent,
  PiPrimaryRequestSnapshot,
  PiPrimarySessionDeps,
  PiPrimarySnapshotStale,
} from "./primary-session.js";
export {
  appendWeaveBlockOnce,
  DEFAULT_PRIMARY_AGENT_NAME,
  isReadOnlyChildAccessAllowed,
  PiPrimarySession,
  probeParentSession,
  renderRequiredSkillsPrompt,
  renderWeavePromptBlock,
  requirePersistentParentSession,
  UNKNOWN_PARENT_SESSION,
} from "./primary-session.js";
export {
  type PiRepeatedSettlementValidationError,
  type PiRepeatedSettlementValidationOptions,
  type PiRepeatedSettlementValidationReport,
  type PiSettlementValidationObservation,
  type PiSettlementValidationRun,
  validateRepeatedSettlements,
} from "./repeated-settlement-validator.js";
export {
  type PiChildPrivateOutputCapture,
  type PiChildPrivateOutputSource,
  type PiChildSettlement,
  PiRpcChild,
  type PiRpcChildDeps,
  type PiRpcChildSpawnInput,
} from "./rpc-child.js";
export type {
  PiPreflightResult,
  PiSafeInitializerDeps,
} from "./safe-initializer.js";
export { PiSafeInitializer } from "./safe-initializer.js";
export type {
  PiGenerationRevokePorts,
  PiSessionShutdownResourcesPort,
  PiSessionShutdownSnapshot,
  PiSessionShutdownTelemetryPort,
  PiSessionShutdownUiPorts,
  PiSessionShutdownWorkflowObservePort,
  PiSessionTransitionContextPort,
  PiSessionTransitionControllerPort,
  PiSessionTransitionGuardDeps,
  PiSessionTransitionHandlers,
  PiSessionTransitionHookResult,
  PiSessionTransitionNoticeCell,
  PiSessionTransitionRuntime,
  PiSessionTransitionRuntimeDeps,
  PiSessionTransitionShutdownCells,
  PiSessionTransitionShutdownHostHooks,
  PiSessionTransitionUiPort,
  PiSessionTransitionVeto,
} from "./session-transition-runtime.js";
export {
  buildGenerationRevokePorts,
  createGuardedTransitionHook,
  createSessionTransitionHandlers,
  createSessionTransitionNoticeCell,
  createSessionTransitionRuntime,
  finalizeBoundedShutdown,
  guardSessionTransition,
  labelSessionBeforeFork,
  labelSessionBeforeSwitch,
  labelSessionBeforeTree,
  notifySessionTransition,
  readTransitionEventString,
  registerSessionTransitionHandlers,
  revokeGenerationAuthority,
  revokeGenerationForReplacement,
  runBoundedSessionShutdown,
  SESSION_TRANSITION_GUARD_FAILED_NOTICE,
  SESSION_TRANSITION_NO_UI_NOTICE,
  SESSION_TRANSITION_PROCEED,
  SESSION_TRANSITION_PROMPT_FAILED_NOTICE,
  SESSION_TRANSITION_STAY,
} from "./session-transition-runtime.js";
export { PiSkillCatalog, toEngineSkillInfo } from "./skill-catalog.js";
export {
  type CanonicalizeError,
  canonicalizeToBytes,
  type JsonValue as PiJsonValue,
  parseStrictJson,
  type StrictJsonParseError,
} from "./strict-json.js";
export type {
  PiThreadSourceFactory,
  PiThreadSourceFactoryError,
  PiThreadSourceFactoryInput,
  PiThreadSources,
} from "./thread-sources.js";
export {
  createProductionPiThreadSourceFactory,
  openPiThreadSources,
} from "./thread-sources.js";
export type {
  PiTrustedDataRootPort,
  PiTrustedDataRootViolation,
} from "./trusted-data-root.js";
export {
  BunPiTrustedDataRootPort,
  createBunPiTrustedDataRootPort,
  FakePiTrustedDataRootPort,
  IdentityPiTrustedDataRootPort,
} from "./trusted-data-root.js";
export type {
  Clock,
  IdGenerator,
  PiAdapterLogger,
  PiAfterProviderResponseEvent,
  PiBeforeAgentStartEvent,
  PiBeforeProviderHeadersEvent,
  PiBeforeProviderRequestEvent,
  PiBuildSystemPromptOptions,
  PiCommandHandler,
  PiCommandInfo,
  PiCommandRegistration,
  PiEventHandler,
  PiExtensionApi,
  PiMode,
  PiModelRegistry,
  PiProviderEventProjection,
  PiProviderEventProjectionError,
  PiProviderHookName,
  PiResourceOrigin,
  PiResourceScope,
  PiSessionContext,
  PiSessionHeader,
  PiSessionManagerPort,
  PiSkillInfo,
  PiSourceInfo,
  PiToolRegistration,
  PiToolResultContent,
  PiTrustState,
  PiUiDialogOptions,
  PiUiNotifyLevel,
  PiUiPort,
  PiUiThemeBgColor,
  PiUiThemeFgColor,
  PiUiThemePort,
} from "./types.js";
export { projectPiProviderEvent } from "./types.js";
export type { Ink, Paint, Tone } from "./ui-paint.js";
export { makePaint, paintTone, plainPaint, toneInk } from "./ui-paint.js";
export type { RailGeometry, Row, Seg, UiLayoutError } from "./ui-rows.js";
export {
  cell,
  clipRow,
  emit,
  fill,
  fitRow,
  fitTo,
  glyph,
  joinColumns,
  joinFit,
  padRow,
  RAIL_GEOMETRY,
  reserveRows,
  rowLR,
  rowWidth,
  safeText,
  safeTrim,
  seg,
  splitRail,
  stackSections,
  TRANSCRIPT_MIN,
  wrapIndented,
  wrapPlain,
} from "./ui-rows.js";
